<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgentNexus.Core\AgentNexus.Core.csproj" />
    <ProjectReference Include="..\AgentNexus.Tooling\AgentNexus.Tooling.csproj" />
  </ItemGroup>

</Project>
